### ISSUE TITLE
lol driver non functional on Edison?

### ISSUE THREAD

**Issue by scalectrix** [intel-iot-devkit/upm#11]
tried following test code - it worked sometimes fine for 2-3 lines. Afterwards the output seems gone.
If I reduce the sleep time I can see all sorts of crazy effects (LEDs on here and there)

#include "mraa.hpp"
#include "upm/lol.h"
#include <unistd.h>

int main(int argc, char** argv) {
	upm::LoL lol;

	for (int i=0; i<LOL_X; i++) { 
		for (int j=0; j<LOL_Y; j++) {
			lol.setPixel(i, j, 1);
			usleep(90000);
			lol.setPixel(i, j, 0);
		}
	}
}

**Comment by Propanu** [comment]
Won't fix as this is a hardware issue, besides, the LoL Shield has been discontinued.
