### ISSUE TITLE
upm::Servo::setAngle has incorrect logic for servo positioning

### ISSUE THREAD

**Issue by tophyr** [intel-iot-devkit/upm#110]
The `setAngle` method in `upm::Servo` uses incorrect logic to position the servo it controls. It appears to send a PWM signal for a calculated number of 8ms periods, then shut off the PWM signal entirely. This behavior is incorrect in that the servo does not have time to move to its intended location, and even if it did the servo would not hold its location once it arrived.

**Comment by jrvandr** [comment]
Thank you for contributing this bug fix!  You're pull request has been merged in.
