### ISSUE TITLE
Hx711 ADC support

### ISSUE THREAD

**Issue by rafaneri** [intel-iot-devkit/upm#139]
Hello I have this [ADC](http://www.dfrobot.com/image/data/SEN0160/hx711_english.pdf) and I was wondering if there plan for support it yet? I had some problems to use it with node.js. I tried do an addon, but the result was the same that using node.js with mraa lib. Can you help me with this? This is the [repository](https://github.com/rafaneri/hx711-addon).

Thank you!

**Comment by jrvandr** [comment]
Hi, thank you for the inquiry!  Currently we don't have support for this sensor.  We are always looking to add new sensors, so we can take a look to see when/if it can be added.  We will take a look at the spec sheet and sensor code from the link you posted and will be happy to provide any assistance we can.
Thank you!

**Comment by rafaneri** [comment]
Hi @jrvandr, I did changes to leave the code as the data sheet, then it return the raw ADC data. Now it's working!
Thank you!

**Comment by jrvandr** [comment]
Great to hear it is working for you!  Submitting a pull request will allow us to get this sensor added to the repository.
Thank you.

**Comment by rafaneri** [comment]
Hello @jrvandr, can you help me with a doubt?
I did a fork on upm, wrote my module and install on galileo, but when try execute the example I got the error on attached image.

[Repository](https://github.com/rafaneri/upm)

![captura de tela 2015-03-21 as 19 08 23](https://cloud.githubusercontent.com/assets/7685408/6767047/ae53d79a-cffd-11e4-9eff-489625342a1d.png)

**Comment by rafaneri** [comment]
Ok! It's a wrong parameter -upm-hx711, it should be -lupm-hx711! I'm going do a pull request!
