### ISSUE TITLE
ST7735 class and screen on Edison

### ISSUE THREAD

**Issue by quantograph** [intel-iot-devkit/upm#144]
Hello,
I'm trying to find any screen (bigger than 64x48), which works with Edison, without the Arduino board.
I'm using Linux with C++ and need a screen attached over SPI directly to Edison.
What are the four numbers in ST7735 constructor?
Did anybody have a working ST7735-based screen on Edison WITHOUT the Arduino board?
Thank you for any information. I spent months looking for a working screen and audio (other than USB cards). Need to show some information and play sounds on Edison without any huge extension boards.

**Comment by Propanu** [comment]
Those are the 4 data pins the LCD is using in the following order:
         * @param csLCD LCD chip select pin
         * @param cSD SD card chip select pin
         * @param rs data/command pin
         * @param rst reset pin

Our library was written with the assumption that the ST7735s is already on a breakout board (e.g. http://www.adafruit.com/products/358)

Regarding your second question, I don't recall of anybody using that particular display with anything else yet, but you should be able to get it working with the mini breakout or the Sparkfun Edison blocks just as well.
