### ISSUE TITLE
Microphone example issue

### ISSUE THREAD

**Issue by ayhoung** [intel-iot-devkit/upm#186]
using the default microphone example, I get this error:
in method 'Microphone_getSampledWindow', argument 4 of type 'uint16_t *'

**Comment by Propanu** [comment]
Hi, you are using an old version of the library that doesn't have array typemaps for JS and python. Please follow the instructions here to update:https://software.intel.com/en-us/articles/managing-devkit-libraries-intel-edison-or-intel-galileo-board
Then run the example again and it will work.
