### ISSUE TITLE
Documentation & function signatures differ

### ISSUE THREAD

**Issue by wahbahdoo** [intel-iot-devkit/upm#196]
See output of doxygen2jsdoc tool.
(Suggestions are autogenerated from parameters in the function signature that don't have doxygen documentation.)

Warning: A110X.installISR has documentation for an unknown parameter: fptr. Did you mean isr?
Warning: ADXL335.setZeroY has documentation for an unknown parameter: zeroX. Did you mean zeroY?
Warning: ADXL335.setZeroZ has documentation for an unknown parameter: zeroX. Did you mean zeroZ?
Warning: GroveLed.GroveLed has documentation for an unknown parameter: gpio. Did you mean pin?
Warning: GroveRelay.GroveRelay has documentation for an unknown parameter: gpio. Did you mean pin?
Warning: GroveButton.GroveButton has documentation for an unknown parameter: gpio. Did you mean pin?
Warning: H3LIS331DL.setDataRate has documentation for an unknown parameter: one. Did you mean odr?
Warning: H3LIS331DL.setPowerMode has documentation for an unknown parameter: one. Did you mean pm?
Warning: HTU21D.HTU21D has documentation for an unknown parameter: mode. 
Warning: SSD1327.setGrayLevel has documentation for an unknown parameter: gray. Did you mean level?
Warning: Jhd1313m1.Jhd1313m1 has documentation for an unknown parameter: address. Did you mean lcdAddress, or rgbAddress?
Warning: Jhd1313m1.Jhd1313m1 has documentation for an unknown parameter: address. Did you mean lcdAddress, or rgbAddress?
Warning: MAX31723.MAX31723 has documentation for an unknown parameter: bus. Did you mean csn?
Warning: MAX31723.MAX31723 has documentation for an unknown parameter: devAddr. Did you mean csn?
Warning: LSM303.LSM303 has documentation for an unknown parameter: i2c. Did you mean bus, or addrMag, or addrAcc, or accScale?
Warning: LSM303.LSM303 has documentation for an unknown parameter: addr. Did you mean bus, or addrMag, or addrAcc, or accScale?
Warning: LSM303.LSM303 has documentation for an unknown parameter: addr. Did you mean bus, or addrMag, or addrAcc, or accScale?
Warning: AM2315.AM2315 has documentation for an unknown parameter: mode. 
Warning: MMA7660.installISR has documentation for an unknown parameter: fptr. Did you mean isr?
Warning: MPL3115A2.convertTempCtoF has documentation for an unknown parameter: iTemp. Did you mean fTemp?
Warning: MPL3115A2.convertPaToinHg has documentation for an unknown parameter: iPressure. Did you mean fPressure?
Warning: NRF24L01.send has documentation for an unknown parameter: *value. Did you mean value?
Warning: NRF24L01.getData has documentation for an unknown parameter: load. Did you mean data?
Warning: RPR220.installISR has documentation for an unknown parameter: fptr. Did you mean isr?
Warning: SM130.SM130 has documentation for an unknown parameter: di. Did you mean bus, or devAddr, or rst, or dready?
Warning: SM130.SM130 has documentation for an unknown parameter: dcki. Did you mean bus, or devAddr, or rst, or dready?
Warning: TSL2561.TSL2561 has documentation for an unknown parameter: integration. Did you mean integrationTime?
Warning: WT5001.checkResponse has documentation for an unknown parameter: index. Did you mean opcode?

**Comment by Propanu** [comment]
Fixed these and many others with 3aef2ea70ef4c0d9d9c90e45fe2b7f8a4cc994fb.
