### ISSUE TITLE
Sidebar does not load sensors for Node documentation in IE10

### ISSUE THREAD

**Issue by Propanu** [intel-iot-devkit/upm#202]
For the Yuidoc generated JavaScript documentation pages, the sidebar with the sensor categories and links doesn't load and display properly in IE 10, but it does work as expected with IE 11.

**Comment by wahbahdoo** [comment]
are you pulling the latest version of the tool? i fixed a bug for ie8 last weekend, would expect ie10 to work if ie8 does.

**Comment by Propanu** [comment]
I thought I did but somehow I missed your latest changes. I don't have your repository set up as a sub component of UPM yet, it will be a while till I get to that. Everything is in place and works nicely now, thanks a lot!
