### ISSUE TITLE
adafruitss.cxx frequency is hard coded

### ISSUE THREAD

**Issue by wolfmanjm** [intel-iot-devkit/upm#211]
It appears that the PWM frequency is hard coded here...
https://github.com/intel-iot-devkit/upm/blob/master/src/adafruitss/adafruitss.cxx#L60

Instead of using the passed in frequency. This means that although the frequency may be changed the pulse width will be incorrect for the given frequency.

I'll fix this and test it before submitting a PR for the fix.

**Comment by Propanu** [comment]
You might want to take a look at the PCA9685 driver provided by @Jon-ICS. He used it to implement the Adafruit MotorShield, since that one also uses the same PWM driver and might come in handy here.

**Comment by Jon-ICS** [comment]
This driver should probably be re-written to use pca9685 :)

**Comment by wolfmanjm** [comment]
this particular bug is not related to the PCA9685, it is specific to determining the pulse width for a servo used later on.

I agree using the PCA9685 would make sense though to avoid duplication, but that is simply a refactor :)

**Comment by wolfmanjm** [comment]
I've fixed and tested the pwm frequency bug. I'm still looking at how hard it is to use the PCA9685 driver. It initially looks like there are some missing features, but I need to investigate further.

**Comment by Propanu** [comment]
Can you please submit a pull request with your fix?
