### ISSUE TITLE
minor type error

### ISSUE THREAD

**Issue by leecom3025** [intel-iot-devkit/upm#215]
https://github.com/intel-iot-devkit/upm/blob/master/src/hcsr04/hcsr04.cxx
line 52, 
    gpio_edge_t edge = MRAA_GPIO_EDGE_BOTH;
should be 
    mraa_gpio_edge_t edge = MRAA_GPIO_EDGE_BOTH;

Please correct it.

**Comment by alext-mkrs** [comment]
This is a duplicate of #214
