### ISSUE TITLE
DS18B20 support

### ISSUE THREAD

**Issue by akulo** [intel-iot-devkit/upm#243]
I would like to see support for One wire DS18B20 Temperature Sensor

**Comment by Propanu** [comment]
This is a popular sensor that unfortunately won't end up in UPM any time soon. One Wire is difficult to implement on a non-RTOS! It might become possible with a newer kernel though.

**Comment by Propanu** [comment]
Update: We found a way that might allow us to control one wire devices on our Linux boards and a driver for this sensor is under development.

**Comment by akulo** [comment]
thats a great news! looking forward to the updated driver.

**Comment by akulo** [comment]
any updates?

**Comment by alext-mkrs** [comment]
I guess this pull request for mraa should open the door for UPM to support it, but not earlier than it's merged: https://github.com/intel-iot-devkit/mraa/pull/415

**Comment by Propanu** [comment]
Unfortunately this won't make it into 0.5.0 but I will merge the implementation (#340) once MRAA adds the necessary functions.

**Comment by Propanu** [comment]
Added to with e679d40d44bd5fb4c71f8567bfe9ceb7f45c75c7!
