### ISSUE TITLE
Internal ISRs should not be exposed to the user

### ISSUE THREAD

**Issue by stefan-andritoiu** [intel-iot-devkit/upm#245]
Several drivers use internal ISRs that are installed when the constructor or a start-type method is called. These sensors do not offer the the possibility of installing any other ISR; don’t have any insatallISR()-type methods like other sensors do. 
In conclusion, the access level should be set to private.

These are:
beatISR() from GrooveEHR
flowISR() from GroveWFS
signalAISR() from RotaryEncoder

**Comment by Propanu** [comment]
Fixed by a79d8abfcd3d3ef393ece0405224ffbbde532fa1.
However this is a good topic as we need a generic way of handling callbacks for all the bindings and not just keeping them internal.
