### ISSUE TITLE
ZFM20::verifyPacket does not calculate checksum

### ISSUE THREAD

**Issue by petreeftime** [intel-iot-devkit/upm#249]
The ZFM20::verifyPacket function does not calculate the packet checksum as advertised in the function description, it only looks at a few fields in the header.
Links: https://github.com/intel-iot-devkit/upm/blob/master/src/zfm20/zfm20.h#L215
https://github.com/intel-iot-devkit/upm/blob/master/src/zfm20/zfm20.cxx#L232

**Comment by Propanu** [comment]
Yeah, it was misleading. I rephrased the documentation in 5fd2d9c4396f902572ca32707f8ff6654e2b588f!
