### ISSUE TITLE
ublox6 warning when using `setTtyFd`

### ISSUE THREAD

**Issue by ThomasLyetPro** [intel-iot-devkit/upm#276]
Got this error when building Vehicle Fleet Tracker example in Eclipse IoT.

    C:\Users\tlyet\Desktop\eclipse-2.0\devkit-x86\sysroots\i586-poky-linux/usr/include/upm/ublox6.h: In member function 'int upm::Ublox6::setTtyFd(int)':
    C:\Users\tlyet\Desktop\eclipse-2.0\devkit-x86\sysroots\i586-poky-linux/usr/include/upm/ublox6.h:123:42: warning: no return statement in function returning non-void [-Wreturn-type]
     int setTtyFd(int fd) { m_ttyFd = fd; };

**Comment by Jon-ICS** [comment]
These should be fixed with PR #283

**Comment by Propanu** [comment]
Fixed by #283.
