### ISSUE TITLE
Adafruit 16 channel servo controller - PCA9685

### ISSUE THREAD

**Issue by stanwgifford** [intel-iot-devkit/upm#28]
This is more of a placeholder/notification that I am developing the library for the above.

if I can work out how will assign to myself - otherwise if unassigned (because I have not worked out how to do it, feel free to assign to me!

Stan

**Comment by stanwgifford** [comment]
Just to leave a progress status - Christmas cause a slowdown as you would imagine.
Anyway the library works - bit of a learning exercise using I2c on the upm platform but have it now. Will not release it as yet because I am tracking down a show-stopper issue - that will require some heavy thinking. Currently have three GWS mini servos connected and running them between 10 and 170 degrees (not 0-180) every second. The issue is that they will go back and forth for a minute or so - then all servos will crawl to zero position and stall. I suspect that the frequency has changed causing the behaviour. The adafruit board uses the internal 25mhz crystal. I have seen another device using this chipset that uses an external 16mhz crystal because 'the internal one can be unstable'. Researching but any insights please direct to me! Stan (Happy new year guys)

**Comment by stanwgifford** [comment]
OK showstopper resolved. Turned out having x (where x is a number between 2-3 or 3 or greater) servos attached at once all slewing between 0 and 180 caused issues. The adafruit page does recommend that a capacitor on the board be used which I believe would be the cure. They do not give the sizing of the cap however primarily because it is application/servo specific - I suspect if I moved a single servo, then did a little wait (The GWS Mini std servos) slew 60 degrees in .19/sec - so if I waited a minimum of .4/sec between moves that would ensure that only a single servo could move at once - I suspect this would work without a cap. 

Anyway, enough of the boring stuff - I have submitted everything to Brendan for check in - hopefully this will be available in an update real soon now!

In retrospect whilst this (looking back) was a family simple piece of code, the external variables - number/type/how many to move at once implies that each implementation could require a fair amount of thinking - tis not like a display which either works or doesn't!

**Comment by arfoll** [comment]
Hey @stanwgifford unless I missed it I did not receive anything - can you resend? Cheers!

**Comment by stanwgifford** [comment]
Very odd - I just checked outbox and all there - investigating..........

**Comment by stanwgifford** [comment]
sent via .zip file

**Comment by arfoll** [comment]
Hey @stanwgifford - I still haven't received them try sending to brendan <at> fridu <dot> net instead you may have more luck.

**Comment by stanwgifford** [comment]
Did you get the attached Zip?


(in this message)

**Comment by arfoll** [comment]
No, I think github strips attachement when sending messages like that.

**Comment by stanwgifford** [comment]
> On 19 Jan 2015, at 19:46, Brendan Le Foll <notifications@github.com> wrote:
> 
> Hey @stanwgifford <https://github.com/stanwgifford> - I still haven't received them try sending to brendan fridu net instead you may have more luck.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/intel-iot-devkit/upm/issues/28#issuecomment-70461249>.
> 
sent to fridu.net=

**Comment by stanwgifford** [comment]
Hi Brendan

I did send to your other email

Did u receive?

Stan

**Comment by stanwgifford** [comment]
Hi - is Brendan still with Intel (I ask because I just had another enhancement assigned to me by a new person) - and I have not heard from Brendan for a while? - I had submitted the code to Brendan as a .zip to a different email address than the github - as github pulls .zip attachements.

**Comment by Propanu** [comment]
Yes, Brendan is still with Intel but focusing mostly on MRAA and other projects now. For UPM related stuff it will be faster to check with me or @jrvandr.

**Comment by stanwgifford** [comment]
So. I have the upm module ready for rolling into upm. I had sent it to Brendan but suspect he may not have it. What is a good email address (not GitHub) to send the zip file containing the code plus examples too?

**Comment by Propanu** [comment]
Try sending to my Intel address, it's listed in my recent sign-offs and should work if you have only code files in the zip.

**Comment by stanwgifford** [comment]
Sorry mate - must be having a blond moment but cannot find your Intel address

**Comment by Propanu** [comment]
mihai.tudor.panu at intel dot com

**Comment by Propanu** [comment]
Just out of curiosity can you list what kind of servos/motors did you hook up to this controller?

**Comment by stanwgifford** [comment]
Just looked - the sample program lists them - gas mini servo type 1

**Comment by stanwgifford** [comment]
That should be GWS (not gas…..)

**Comment by Propanu** [comment]
I have opened #116 with what you sent plus minor touch-ups. Let me know if it looks good to you and I'll get merged to master.

**Comment by stanwgifford** [comment]
Looks good to me
