### ISSUE TITLE
Adding Sensors - AM2315, AS3935, and MCP4725

### ISSUE THREAD

**Issue by whpenner** [intel-iot-devkit/upm#29]
I have nearly completed the support for the Aosong AM2315 Temp and Humidity sensor.  The MCP4725 A2D looks to be pretty simple, so I'll do that next.  The AS3935 lightning sensor will be last of this group.

**Comment by Propanu** [comment]
@whpenner any plans to add the 2 other sensors or can this be closed?

**Comment by whpenner** [comment]
I should probably pull this for now.  The AM2315 was done and is part of UPM.  I have the AS3935 half coded, but it needs a bunch of tuning and clean up – nowhere near ready.  I never got to the MCP4725.

So, we could close this for now and I’ll come back to these when I have more time.

Bill

**Comment by Propanu** [comment]
Thanks for the update, closed for now!
