### ISSUE TITLE
Use Grove Ultrasonic ranger with Nodejs and Python 

### ISSUE THREAD

**Issue by badr-badri** [intel-iot-devkit/upm#290]
HI guys,
Is there any way to use the ultrasonic ranger sensor with python or node.js ?
Thanks in advance

**Comment by Propanu** [comment]
Hi,
We have a driver for the HSCR-04, URM37 and MaxSonar that work with all the supported languages. There was also a contribution with a driver for the Grove version of the ultrasonic sensor but it hasn't been merged yet because it needs some clean-up. Which one do you have?

**Comment by badr-badri** [comment]
Thanks for your reply.
I have this one :
http://www.gotronic.fr/art-telemetre-a-ultrasons-grove-sen10737p-18976.htm
I hope that you have a solution for that one.
Thanks again.

**Comment by Propanu** [comment]
That's the one. Here's the code: https://github.com/arcatdmz/upm/commit/0277b7fcd7806a5ff11cb9a7eb36c650f3384859 in case you want to build the sensor driver yourself until we merge it.

**Comment by Propanu** [comment]
The ultrasonic ranger sensor was added to the main branch. I do expect it to be merged with HSCR04 at some point though since they work the same way.
