### ISSUE TITLE
jsupm_9685 

### ISSUE THREAD

**Issue by kobymaster** [intel-iot-devkit/upm#295]
dont work for intel galileo gen 1
var myLEDController_obj = new LEDController_lib.PCA9685(I2CBus, I2CAddr);
^
Error: Illegal arguments for construction of _exports_PCA9685
at Object. (/home/root/prueba1.js:27:27)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:935:3

**Comment by malikabhi05** [comment]
Hi kobymaster,

You probably are using the default i2c address in the constructor call. You would have to figure out the address for your device. You can use tools such as i2cdetect to figure out the address. The API documentation for this is at: http://iotdk.intel.com/docs/master/upm/node/classes/pca9685.html

**Comment by xbolshe** [comment]
A part of upm/examples/javascript/pca9685.js:

![bug1](https://cloud.githubusercontent.com/assets/10796236/10864577/7160d6ec-8003-11e5-98a7-ae8b6ac3d436.jpg)

This problem is not related with an incorrect I2C address. It seems it is related with an incorrect function wrapping in pca9685 node-js module.

**Comment by Propanu** [comment]
@xbolshe is this with SWIG 3.0.7 and Node 4?

**Comment by xbolshe** [comment]
With SWIG 3.0.8 and Node 4.1

**Comment by xbolshe** [comment]
Same with Node 5.0.0

![aaaa](https://cloud.githubusercontent.com/assets/10796236/11074711/26f28022-8802-11e5-8e20-02c14885e73a.jpg)

**Comment by xbolshe** [comment]
Hm... syslog makes the problem more clear: I2C address seems bad.

![bbbbb](https://cloud.githubusercontent.com/assets/10796236/11074788/9ecdb756-8802-11e5-8b91-e454f7719143.jpg)

**Comment by malikabhi05** [comment]
Hi, if the i2c address is correct then it should work as expected in all languages, it has been tested and it works with node 0.10.36 and swig 3.0.5
