### ISSUE TITLE
Add backlight support to LCD libraries.

### ISSUE THREAD

**Issue by auzroz** [intel-iot-devkit/upm#296]
Currently using the "jsupm_i2clcd" library to control a LCM1602 lcd with a backpack. [This One.](http://www.sainsmart.com/sainsmart-iic-i2c-twi-serial-2004-20x4-lcd-module-shield-for-arduino-uno-mega-r3.html)

I can manually control the backlight by writing either 0x00 (backlight off) or 0x08 (backlight on). It would be nice to have this functionality added to the library, or at least expose the send/command structure as a public function to allow for expanded/custom functionality that may be available in different variants.

See Also: [LiquidCrystal_I2C](https://github.com/fdebrabander/Arduino-LiquidCrystal-I2C-library/blob/master/LiquidCrystal_I2C.cpp) for setBacklight/backlight/noBacklight functions.

**Comment by Propanu** [comment]
Added functions to turn backlight on/off with de986764d4c84217e979f84c7a8956cadc69fd24 and they are now part of UPM 0.7.0. Thanks for the suggestion!
