### ISSUE TITLE
Microphone sensor python and javascript

### ISSUE THREAD

**Issue by alexandruradovici** [intel-iot-devkit/upm#31]
How do I send a buffer for the Microphone in python and javascript?

import pyupm_mic
m = pyupm_mic.Microphone (3)
buffer = range (1, 100)
m.getSampledWindow (44100, 100, buffer)

this results in an error

**Comment by Propanu** [comment]
We have updated the JS bindings and added an example for this library. Python fix will follow soon!

**Comment by jrvandr** [comment]
python example is now available:
https://github.com/intel-iot-devkit/upm/blob/master/examples/python/mic.py

closing bug
