### ISSUE TITLE
Why my UPM sensor not on the list ?

### ISSUE THREAD

**Issue by neuberfran** [intel-iot-devkit/upm#312]
I bought this driver http://www.mindsensors.com/search?controller=search&orderby=position&orderway=desc&search_query=smartdrive&submit_search

and create a upm sensor to that: https://drive.google.com/file/d/0B9gPdWq4OH-XM2lFdVhMbU5Hekk/view

in future I will TRY do this: https://www.youtube.com/watch?v=tQX34zQGPtw using windshield wiper motor (instead of LED BlinkM)

I did pull request

**Comment by Propanu** [comment]
Hi, I don't see your pull request, could you please make sure it's open against the main intel-iot-devkit/upm repository? Thanks!

**Comment by neuberfran** [comment]
Whats steps do you follow to pull request new  UPM/Sensor ??

**Comment by sasmita** [comment]
Please make sure, your changes are committed in a new branch. You can click on "new pull request" button in the repo header in https://github.com/intel-iot-devkit/upm.

**Comment by Propanu** [comment]
Do you need additional help with this?

**Comment by Propanu** [comment]
Added with #371!
