### ISSUE TITLE
Build error with Yocto 2.0

### ISSUE THREAD

**Issue by sakoman** [intel-iot-devkit/upm#329]
Error message:

ERROR: QA Issue: non debug package contains .debug directory: upm path work/core2-32-poky-linux/upm/0.4.0-r0/packages-split/upm/usr/lib/python3.4/site-packages/.debug/_pyupm_lm35.so [debug-files]
ERROR: QA run found fatal errors. Please consider fixing them.

**Comment by Propanu** [comment]
Does this happen only for the LM35 module, or do you see it for all the python bindings?

**Comment by sakoman** [comment]
I just get a single error on the LM35 module

**Comment by xbolshe** [comment]
It looks like bitbake recipe bug, not upm package.

**Comment by sakoman** [comment]
Ah, yes I filed the bug in the wrong place!

I use the meta-intel-iot-middleware layer (master branch).  Recipe is here:

http://git.yoctoproject.org/cgit/cgit.cgi/meta-intel-iot-middleware/tree/recipes-devtools/upm/upm_0.4.0.bb

**Comment by Propanu** [comment]
Definitely a Yocto issue, just did a full install and I can't replicate it. Might want to sync with @arfoll on this as he wrote the bitbake recipes for the middleware libs.

**Comment by alext-mkrs** [comment]
Based on my experience building upm for my package repo, the reason is most probably that the recipe was tested with the default Python 2, while in this case it's Python 3 it picks up. But the fix is anyway should be in the recipe, UPM rather can do nothing about this.

**Comment by Propanu** [comment]
Yes, we do build with Python 2.7 instead of 3 to ensure compatibility with the IoTDK images.
