### ISSUE TITLE
UPM driver for SSD1351 OLED display

### ISSUE THREAD

**Issue by stanwgifford** [intel-iot-devkit/upm#34]
This is a placeholder for a upm module to control the SSD1351 oled display. This is a SPI device and the module I will be using when writing the code is a freetronics module ( http://freetronics.com/oled128 )

**Comment by stanwgifford** [comment]
Note - I am probably going to put this on hold until a new kernel comes that gives a decent SPI data rate - currently using the arduino code, the baud rate across SPI to the OLED looks like it is running at 300 baud (well pretty slowly). Note - the standard libraries for this OLED do work well in the Arduino environment - just slow.............

**Comment by sukeshak** [comment]
The Oled used with Sparkfun Edison block also uses SPI and it works great without any lag. 
I am planning to use a 1.5" 128x64 (blue) instead of that... You think I should also wait for the new kernel?

**Comment by sukeshak** [comment]
Any updates on this? Looking forward for this driver :)

**Comment by sukeshak** [comment]
@stanwgifford  any update on this?

**Comment by Propanu** [comment]
Driver was made available today with basic functionality implemented (lightweight version of Adafruit's GFX lib)!

**Comment by sukeshak** [comment]
Thank you for getting this done... Sounds great... will test it and revert in a day
