### ISSUE TITLE
Ultrasonic sensor python example

### ISSUE THREAD

**Issue by BTWS** [intel-iot-devkit/upm#342]
Is it possible to add a python example for an ultrasonic sensor like a HC-SR04?

I noticed there is a c++ example for GroveUltrasonic. Is this equivalent to the HC-SR04?

**Comment by Propanu** [comment]
Hi, yes, the Grove Ultrasonic sensor works the same way as the HCSR04 and the implementation is basically the same. The two separate drivers will be eventually merged into one and we will try to add the missing python sample as well when this happens.

**Comment by malikabhi05** [comment]
Python example added for hcsr04. hcsr04 and grove ultrasonic to be merged soon.
