### ISSUE TITLE
HCSR04 getDistance stuck in infinite loop.

### ISSUE THREAD

**Issue by jjrob13** [intel-iot-devkit/upm#343]
I have been working with the hcsr04 ultrasonic sensor with the Intel Edison and have recently had some issues with calls to the getDistance function blocking indefinitely.  Specifically, execution is halting at the following point:

```
while (!m_doWork) {
        usleep (5);
    }
```

So m_doWork is never changing from zero and the execution never passes this point.  The issue was fixed briefly after replacing the sensor, but now I am seeing the same behavior.  This is my first time submitting an issue, so forgive me if I am doing something incorrectly.  Please let me know how I can improve future submissions.  Additionally, I can provide a stack trace if it will be helpful.

Thanks,

JJ

**Comment by Propanu** [comment]
Hi JJ,

Try using the `groveultrasonic` library instead. Functionality is nearly the same but that driver will time-out in case it doesn't get a reply from the sensor instead of getting stuck. We plan to merge the two drivers in a future version.
