### ISSUE TITLE
Problem with installation path

### ISSUE THREAD

**Issue by xbolshe** [intel-iot-devkit/upm#376]
After https://github.com/intel-iot-devkit/upm/commit/a48f457057748d190e9faeec6495ef9a8c504de6 NODE_MODULE_INSTALL_PATH is related with NODE_ROOT_DIR. And it creates a problem with changed sysroot dir and cross-compiled nodejs.

Here is a part of install_manifest.txt:

/sde/r1.2.0/iot_1.2.0_kernel_3.19.8/build/tmp/sysroots/quark/usr/lib/node_modules/jsupm_grovevdiv/package.json
/sde/r1.2.0/iot_1.2.0_kernel_3.19.8/build/tmp/sysroots/quark/usr/lib/node_modules/jsupm_grovevdiv/jsupm_grovevdiv.node
/usr/lib/libupm-grovevdiv.so.0.6.0
/usr/lib/libupm-grovevdiv.so.0
/usr/lib/libupm-grovevdiv.so
/usr/include/upm/grovevdiv.h
/usr/lib/pkgconfig/upm-lpd8806.pc
/sde/r1.2.0/iot_1.2.0_kernel_3.19.8/build/tmp/sysroots/quark/usr/lib/node_modules/jsupm_lpd8806/package.json
/sde/r1.2.0/iot_1.2.0_kernel_3.19.8/build/tmp/sysroots/quark/usr/lib/node_modules/jsupm_lpd8806/jsupm_lpd8806.node
/usr/lib/libupm-lpd8806.so.0.6.0
/usr/lib/libupm-lpd8806.so.0
/usr/lib/libupm-lpd8806.so
/usr/include/upm/lpd8806.h
/usr/lib/pkgconfig/upm-groveeldriver.pc
/sde/r1.2.0/iot_1.2.0_kernel_3.19.8/build/tmp/sysroots/quark/usr/lib/node_modules/jsupm_groveeldriver/package.json
/sde/r1.2.0/iot_1.2.0_kernel_3.19.8/build/tmp/sysroots/quark/usr/lib/node_modules/jsupm_groveeldriver/jsupm_groveeldriver.node
/usr/lib/libupm-groveeldriver.so.0.6.0
/usr/lib/libupm-groveeldriver.so.0
/usr/lib/libupm-groveeldriver.so
/usr/include/upm/groveeldriver.h
/usr/lib/pkgconfig/upm-grovescam.pc
/sde/r1.2.0/iot_1.2.0_kernel_3.19.8/build/tmp/sysroots/quark/usr/lib/node_modules/jsupm_grovescam/package.json
/sde/r1.2.0/iot_1.2.0_kernel_3.19.8/build/tmp/sysroots/quark/usr/lib/node_modules/jsupm_grovescam/jsupm_grovescam.node
/usr/lib/libupm-grovescam.so.0.6.0
/usr/lib/libupm-grovescam.so.0
/usr/lib/libupm-grovescam.so
/usr/include/upm/grovescam.h
/usr/lib/pkgconfig/upm-flex.pc

As you may see NODE_ROOT_DIR is added to modules paths.

**Comment by xbolshe** [comment]
I have checked my environment. Here what I have in macro(upm_SWIG_NODE):

NODE_MODULE_INSTALL_PATH = /sde/r1.2.0/iot_1.2.0_kernel_3.19.8/build/tmp/sysroots/quark
/usr/lib/any/

CMAKE_CURRENT_BINARY_DIR = /sde/r1.2.0/iot_1.2.0_kernel_3.19.8/build/tmp/work/i586-poky
-linux/upm/0.6.0+gitAUTOINC+230bc4f569-r0/git/build/src/any

PROJECT_SOURCE_DIR = /sde/r1.2.0/iot_1.2.0_kernel_3.19.8/build/tmp/work/i586-poky-linux
/upm/0.6.0+gitAUTOINC+230bc4f569-r0/git

NODE_ROOT_DIR = /sde/r1.2.0/iot_1.2.0_kernel_3.19.8/build/tmp/sysroots/quark/usr

CMAKE_SYSROOT = <empty>

**Comment by xbolshe** [comment]
If I return DESTINATION lib/node_modules/jsupm_${libname} back, the problem goes away.

**Comment by Propanu** [comment]
I'm guessing something similar to https://github.com/intel-iot-devkit/mraa/commit/14de175425d0e315e5a130cdd9d0c6c8b7026cce will fix this issue.

**Comment by Propanu** [comment]
Please let me know if 02974f242efd59aaf1bc54e98796cd8c8c43310a fixes this for you.

**Comment by xbolshe** [comment]
It does not fix the problem:

usr/lib/node_modules/jsupm_grovegprs/package.json
/sdc/ww25.5-15/edison-src/out/linux64/build/tmp/sysroots/edison/usr/lib/node_modules/jsupm_grovegprs/jsupm_grovegprs.node
/usr/lib/libupm-grovegprs.so.0.6.0
/usr/lib/libupm-grovegprs.so.0
/usr/lib/libupm-grovegprs.so
/usr/include/upm/grovegprs.h
/usr/lib/pkgconfig/upm-lm35.pc
/usr/lib/node_modules/jsupm_lm35/package.json
/sdc/ww25.5-15/edison-src/out/linux64/build/tmp/sysroots/edison/usr/lib/node_modules/jsupm_lm35/jsupm_lm35.node
/usr/lib/libupm-lm35.so.0.6.0
/usr/lib/libupm-lm35.so.0
/usr/lib/libupm-lm35.so
/usr/include/upm/lm35.h
/usr/lib/pkgconfig/upm-groveeldriver.pc
/usr/lib/node_modules/jsupm_groveeldriver/package.json
/sdc/ww25.5-15/edison-src/out/linux64/build/tmp/sysroots/edison/usr/lib/node_modules/jsupm_groveeldriver/jsupm_groveeldriver.node
/usr/lib/libupm-groveeldriver.so.0.6.0
/usr/lib/libupm-groveeldriver.so.0
/usr/lib/libupm-groveeldriver.so
/usr/include/upm/groveeldriver.h
y-linux/upm/0.6.0+gitAUTOINC+02974f242e-r0/git/build$

**Comment by xbolshe** [comment]
Fix for package.json, but not for any.node

**Comment by Propanu** [comment]
Missed a `set` command that was still using node_root. Should be fixed for both now with db8d7087988e846c28a3a7ae61cf0d82905a154c. Thanks!

**Comment by xbolshe** [comment]
Yes, now it works correctly.

**Comment by Propanu** [comment]
Thanks for the confirmation, closed!
