### ISSUE TITLE
Add CMAKE_CXX_FLAGS for autodetecting board architecture

### ISSUE THREAD

**Issue by 4refr0nt** [intel-iot-devkit/upm#388]
Add CMAKE_CXX_FLAGS:STRING=-march=native for autodetecting board architecture.
This actual for Raspberry Pi and other ARM-based platforms

**Comment by Propanu** [comment]
Can be added as an option when an ARM board is detected, will look into it.

**Comment by Propanu** [comment]
Done, this is now part of UPM 0.7.0.
