### ISSUE TITLE
LCD:SSD1306 error on Raspberry Pi 2

### ISSUE THREAD

**Issue by 4refr0nt** [intel-iot-devkit/upm#390]
```
m_i2c_lcd_control.frequency(mraa::I2C_FAST)
```
cause fatal error on Raspberry Pi 2

**Comment by Propanu** [comment]
I feel like this is more of a MRAA issue.

**Comment by Propanu** [comment]
Can you paste the error message?

**Comment by Propanu** [comment]
This should no longer be an issue since 2b642ab7a4e63e506edd0b0cf1816231ff9b6ab3.
