### ISSUE TITLE
es08a.js crashes the edison

### ISSUE THREAD

**Issue by teuteuguy** [intel-iot-devkit/upm#419]
Have updated the Edison to last firmware, and opkg update, opkg upgrade.

just running that file as is, with the servo on port 5 ... crashes the edison: ie. reboots

**Comment by Propanu** [comment]
Please don't hook up the ES08A to the Intel Edison without using the external power supply. USB alone can't drive the motor, and you risk burning the servo, or even worse, damaging the board! While 1 (tiny) servo alone might be OK when using external power, I highly recommend using a dedicated servo shield for anything that requires more.

**Comment by Propanu** [comment]
Updated on list of known limitations too.
