### ISSUE TITLE
cmake makes swing a dependency even if it is not required

### ISSUE THREAD

**Issue by whbruce** [intel-iot-devkit/upm#436]
If BUILDDOC, BUILDSWIGPYTHON, BUILDSWIGNODE BUILDSWIGJAVA are all OFF there is no need for swig. But as BUILDSWIG is set to ON by default, cmake thinks it is dependency even when its not required.

**Comment by Propanu** [comment]
IMHO the BUILDSWIG variable is superfluous and I agree that it makes perfect sense not to have a SWIG dependency when bindings are not selected. Will look into it.

**Comment by jontrulson** [comment]
A fix for this has just been pushed (49e04593d866cc4c39a77042e2b19cb395c0951a).  It removes the BUILDSWIG option.
