### ISSUE TITLE
Add option to allow option of dynamically linking to upm shared library in nodejs modules

### ISSUE THREAD

**Issue by whbruce** [intel-iot-devkit/upm#443]
I can see the advantage of statically linking to upm sensor library as it requires no dependencies. However dynamically linking provides a smaller .node file and works just fine. This is a better solution if .so files need to be installed for test (or other) purposes.

**Comment by Propanu** [comment]
I'll have to check if this can be added when I try to resolve #325.

**Comment by Propanu** [comment]
Done, @pylbert updated this with his c1f9d15f6759cc59829d4da4f393ded2984054e0 commit. The new binaries are about 13% smaller now. Thanks @whbruce for bringing it up!
