### ISSUE TITLE
Grove Accelerometer support

### ISSUE THREAD

**Issue by ashishdatta** [intel-iot-devkit/upm#5]
Hello I have this accelerometer (http://www.seeedstudio.com/depot/Grove-3Axis-Digital-Accelerometer16g-p-1156.html?cPath=25_132) and I was wondering if there is support for it yet?

**Comment by Propanu** [comment]
We recently added the driver for the Grove 3-axis Digital Accelerometer (16g). It's named ADXL345 in the library files, examples are included too!
