### ISSUE TITLE
LSM303D  chip //  6 - Axis // same Hex address to Accelerometer and Compas

### ISSUE THREAD

**Issue by caymo04** [intel-iot-devkit/upm#510]
Good morning,

I think that is necesary a new library for LSM303D chip.

The Grove 6-Axis V2.0 uses the newer LSM303D chip instead of the LSM303DLHC which was used in V1 (and to write the UPM driver). The major difference is that LSM303D uses a single address for both acceleration and compass data (hence why it worked with 0x1e, 0x1e) but you won't get any valid data for the magnetometer.

Best regards,

**Comment by Propanu** [comment]
This was added with 5cc4e2120a356d8d4d695f337593b6f49ae70304.
