### ISSUE TITLE
Looking for example usage of  executeCMDlist for LCD display ST7735

### ISSUE THREAD

**Issue by andreas-rng** [intel-iot-devkit/upm#514]
Can someone give me an example of how to use [executeCMDlist ](https://iotdk.intel.com/docs/master/upm/python/pyupm_st7735.html) function? I don´t know how to supply the pointer in python as an argument to the function.

Thank you,

Andreas

**Comment by Propanu** [comment]
Hi, I've staged changes that will add typemaps for uint8_t arrays for python. They will be included with the next version tag. With these in place, you will be able to build a list of commands similarly to the example given in #352.

**Comment by andreas-rng** [comment]
Thanks.
