### ISSUE TITLE
Problems back on HTU21D-F follow up of #457

### ISSUE THREAD

**Issue by g-vidal** [intel-iot-devkit/upm#548]
Hi all,
I spent some time few months ago on HTU21D-F and even if not detected on i2c bus measurements were possible. I have started another project and when I plugged again HTU21D-F  it did not show up and sent error messages. 
I have checked my sensors with an arduino, all of them work well but when using mraa/upm on Edison or RaspberryPi  no measurement is possible. The sensor seems to be  connected but all write failed with the same error  :
ValueError: UPM Invalid Argument: Unknown error in I2c::readReg()

Am I the only one to get this error or is-it a general problem?
Thanks

**Comment by Propanu** [comment]
Hi @g-vidal, I've tested the sensor on the Edison with the Arduino breakout and noticed the same capacitance problem as we encountered on many other I2C sensors. If I power it from 5V, it will read the data once or twice before it throws the error. At 3V3 I can get several readings before it bails out.

My suggestions are:
* Wire the sensor to 3V3 and wrap the sensorData() function call in a try..catch block. This way your application will continue to run even when it fails to read and you can log the error/retry. No hardware needed, just a bit of extra code.
* Use an I2C bus repeater/redriver/hub that isolates capacitance on the I2C bus. A good example is the PCA9517 (I have the one from [here](https://international.switch-science.com/catalog/2375/)). With this, I can get all the sensors listed in the known limitations to work on the Edison with the Arduino breakout with no issues. Perhaps the TCA9548A mux you have works too.

Tested with the latest MRAA/UPM libs and Edison image. I've also updated the known limitations page, and added the Py/JS examples for this sensor.
