### ISSUE TITLE
Documentation for HTU21D sensor says it returns humidity in degC. Is that right

### ISSUE THREAD

**Issue by stefan-andritoiu** [intel-iot-devkit/upm#561]
https://github.com/intel-iot-devkit/upm/blob/master/src/htu21d/htu21d.hpp#L103

I would change it but I don't know if it's % or %%

Also this line is weirdly phrased:
https://github.com/intel-iot-devkit/upm/blob/master/src/htu21d/htu21d.hpp#L111

**Comment by Propanu** [comment]
Updated to match sensor datasheet in 8186d093ec1a2fca82ff15ea03dec86f3ca4c401. Hope this clarifies things. Thanks!
