### ISSUE TITLE
RE: Using BBB w/ Grove Cape v2 on Debian Stretch...

### ISSUE THREAD

**Issue by silver2row** [intel-iot-devkit/upm#583]
Hello,

I am trying to use this software I found for grovegprs.js. I installed mraa with npm since I have node on my BBB. I am using a Grove Cape for that specific board (Grove Cape v2). 

Is anyone working with Debian, the BBB, and the Grove Cape v2?

Seth

P.S. I need a bit of guidance right now with this software. I keep getting an error message: cannot find module 'jsupm_grovegprs'.

**Comment by Propanu** [comment]
Hi Seth, you'll also need to install jsupm_grovegprs with npm to be able to run the samples in this repository. There are also some known issues with some of the UPM packages on npm, but I don't recall if grovegprs is on that list. See [this section](https://github.com/intel-iot-devkit/upm/blob/master/docs/installing.md#nodejs-bindings-only-npm) for further reference.
