### ISSUE TITLE
Regression due to #812 in mraa

### ISSUE THREAD

**Issue by Mani-Sadhasivam** [intel-iot-devkit/upm#597]
mraa commit #812 introduces API change and fails to modify the corresponding drivers which in turn breaks the build. Following is the error observed while trying to build upm on Dragonboard410c.

https://pastebin.ubuntu.com/25470713/

**Comment by Mani-Sadhasivam** [comment]
@pylbert Are u aware of this?

**Comment by dnoliver** [comment]
@Mani-Sadhasivam are you talking about this PR in mraa? https://github.com/intel-iot-devkit/mraa/pull/812

**Comment by Propanu** [comment]
Hi @Mani-Sadhasivam, we are aware of the issue and working on updating the UPM IIO drivers to match the new API.

**Comment by dnoliver** [comment]
@Propanu is this fixed?

**Comment by Propanu** [comment]
Yes, closing.
