### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by KillingJacky** [intel-iot-devkit/upm#603]
debian 9, gcc 6.3.0

![image](https://user-images.githubusercontent.com/5130185/30724723-7811fd46-9f72-11e7-8113-aa0e4de777b2.png)

**Comment by Propanu** [comment]
Hi @KillingJacky, please use the `iio-changes` branch for builds until we update the docker images for CI. We'll patch `master` within a couple of days.

**Comment by KillingJacky** [comment]
Oh good to know, and I will close my PR https://github.com/intel-iot-devkit/upm/pull/604
