### ISSUE TITLE
[Question] Support for LIS3DH and MAX7219/21

### ISSUE THREAD

**Issue by alext-mkrs** [intel-iot-devkit/upm#617]
@propanu, @w4ilun, I've got my hands on those two subj modules and noticed there seems to be no support for either of them (there's LIS2DS12, which is very close, but still a bit different from LIS3DH and the latter seems to be more widespread being cheaper) in UPM.

Is that correct? If so, are you interested in getting those in, I could give it a shot if no one works on that or plans to.

**Comment by w4ilun** [comment]
@alext-mkrs I don't think those 2 modules are in development, would be great if you could add them!

**Comment by alext-mkrs** [comment]
Good, thanks for the information :) I'll follow the standard PR flow then, when it's ready.
