### ISSUE TITLE
ZFM20: mraa_uart_init() failed

### ISSUE THREAD

**Issue by Mohamad777** [intel-iot-devkit/upm#621]
I get the following error when I use **upm::ZFM20 fp(0);** in running time (C++):

    terminate called after throwing an instance of 'std::invalid_argument'
       what():  ZFM20: mraa_uart_init() failed

I've found that it may be because of the code bellow from mraa library (It means I get the error message "uart: device path undefined" in syslog:

    mraa_uart_init_raw(const char* path)
    {
        mraa_result_t status = MRAA_SUCCESS;
        mraa_uart_context dev = NULL;
    
        if (!path) {
            syslog(LOG_ERR, "uart: device path undefined");
            status = MRAA_ERROR_INVALID_PARAMETER;
            goto init_raw_cleanup;
        }
    ...

In mraa library I can solve the problem by using **mraa_uart_init_raw("/dev/ttyXXX")**. But here I don't have access to modify the code, and ZFM20 just gets int argument.

Would yo please help me solve this problem?

Is it possible to change the source code of the library to solve this problem?

Thanks in advance.

**Comment by Propanu** [comment]
Hi @Mohamad777, what board are you running this on? I can merge #587 from @pylbert which adds several improvements to this library and there shouldn't be an issue adding the extra string based constructor to initialize raw devices directly.
